---
title: "Week8"
author: "Talal Elammas"
date: "March 23, 2019"
output: html_document
---




```{r}
library("ggplot2")

##1) Save the data to a CSV file. 


## This is heart data from kaggle for sample of people with heart disease include some medical informations from Clevland Research Center database, can be found on kaggle https://www.kaggle.com/ronitf/heart-disease-uci/version/1

heart <- data.frame(read.csv(file = 'C:/Users/Talal/Documents/GitHub/Data_Visualization/heart.csv'))


```



```{r}
## 1: Draw a relation between the age and the resting blood pressure to know the development of high blood pressure in the elderly, cluster the results in 3 clusters, for the graph to be more clear, data will be 50 points.


library(cluster)    # clustering algorithms

# select the first 50 lines from the table.
age <- heart[1:50,1]
trestbps <- heart [1:50,4]

## create the data frame, get the summary to understand the data,
bloodpressure <- data.frame(age,trestbps)
summary(bloodpressure)

# Find the kmeans , using 125 trails before start clustering for 3 clusters.

kmeansobj <- kmeans(bloodpressure, centers = 3, nstart = 125)
names(kmeansobj)
kmeansobj$cluster

# Plot the data 
par (mar = rep(0.2, 4))
plot(age, trestbps, col = kmeansobj$cluster, pch=19, cex = 2.5)


# Plot the cluster points 
points(kmeansobj$cluster, col = 1:3 , pch = 3, cex =3 )



```
