---
title: "Final_Project_Model"
author: "Talal Elammas"
author: "Hemangi Mhatre"

date: "April 24, 2019"
output: html_document
---



```{r}


## Save the data to a CSV file. 


##  Data were provided by the Centers for Disease Control and Prevention (CDC), Division of Population Health, Epidemiology and Surveillance Branch. The project was funded by the Robert Wood Johnson Foundation (RWJF) in conjunction with the CDC Foundation. 500 cities project city-level data in GIS-friendly format can be joined with city spatial data (https://chronicdata.cdc.gov/500-Cities/500-Cities-City-Boundaries/n44h-hy2j) in a geographic information system (GIS) to produce maps of 27 measures at the city-level. There are 4 measures (high blood pressure, taking high blood pressure medication, high cholesterol, cholesterol screening) in this 2018 release from the 2015 BRFSS that were the same as the 2017 release. 

# download the file, add it to your directory, update the directory in the , make sures the slash between directories is forword slash
# data Dictionary can be found on https://chronicdata.cdc.gov/500-Cities/500-Cities-City-level-Data-GIS-Friendly-Format-201/dxpw-cm5u

Project <- data.frame(read.csv(file =  'C:/Users/mhatr/OneDrive/Desktop/TCG PROJECT/selecteddata2.csv') , header = TRUE,  stringsAsFactors = FALSE)



Project

```



```{r}

State <- c (Project[,1])

city <- c (Project[,2])

PlaceFIPS <- c (Project[,3])

population <- c (Project[,4])

ppl_No_Insurance <- c (Project[,5])

ppl_BPHIGH_age_adjusted_prevalence <- c (Project[,6])

ppl_cancer_age_adjusted_prevalence <- c (Project[,7])

ppl_Asthma_age_adjusted_prevalence <- c (Project[,8])

ppl_smoking_age_adjusted_Prevalence <- c (Project[,9])

ppl_Diabetes_age_adjusted_prevalence <-  c (Project[,10])

ppl_Stroke_age_adjusted_prevalence <-  c (Project[,11])

summary(Project)


```



```{r}

# Consider x as table1 = ppl_smoking_age_adjusted_Prevalence
# Consider y as table1 = ppl_Asthma_age_adjusted_prevalence

x <- ppl_smoking_age_adjusted_Prevalence   
y <- ppl_Asthma_age_adjusted_prevalence

##plot x and y
plot( x, y, xlab = "ppl_smoking_age_adjusted_Prevalence", ylab = "ppl_Asthma_age_adjusted_prevalence",  bg = "lightblue", col = "black", cex = 1, pch = 23, frame = FALSE, main = "regression model for age adjusted prevalance of smoking among people and age adjusted prevalance of Asthma among people",cex.main=0.7)

n <- length (y)
fit <- lm(y ~ x+ population)
e <- resid (fit)
yhat <- predict (fit)

#create a plot between the age adjusted prevalance of smoking among people and age adjusted prevalance of Asthma among people


plot( x, e, xlab = "ppl_smoking_age_adjusted_Prevalence", ylab = "ppl_Asthma_age_adjusted_prevalence", bg = "lightblue", col = "black", cex = 1, pch = 21, frame = FALSE,main="residual plot for age adjusted prevalance of smoking among people and age adjusted prevalance of Asthma among people",cex.main=0.7)


#add the regression lines

abline (h = 0, lwd = 2)

#draw the red lines

for (i in 1 : n) 
  lines (c(x[i], x[i]), c(e[i],0), col = "red", lwd = 1)


summary(fit) 
# this results before adding the population factor 
## Residual standard error: 1.025 on 498 degrees of freedom
##Multiple R-squared:  0.3495,	adjusted R-squared:  0.3482 
##F-statistic: 267.6 on 1 and 498 DF,  p-value: < 2.2e-16


# this results after adding the population factor 
##Residual standard error: 1.025 on 497 degrees of freedom
##Multiple R-squared:  0.3517,	adjusted R-squared:  0.3491 
##F-statistic: 134.8 on 2 and 497 DF,  p-value: < 2.2e-16
```




```{r}

# Consider x as table1 = ppl_smoking_age_adjusted_Prevalence
# Consider y as table1 = ppl_BPHIGH_age_adjusted_prevalence

x <- ppl_smoking_age_adjusted_Prevalence
y <- ppl_BPHIGH_age_adjusted_prevalence

##plot x and y
plot( x, y, xlab = "ppl_smoking_age_adjusted_Prevalence", ylab = "ppl_BPHIGH_age_adjusted_prevalence",  bg = "lightblue", col = "black", cex = 1, pch = 21, frame = FALSE,main = "regression model for age adjusted prevalance of smoking among people and age adjusted prevalance of High BP among people",cex.main=0.7)

n <- length (y)
fit <- lm(y ~ x+ppl_Diabetes_age_adjusted_prevalence  )
e <- resid (fit)
yhat <- predict (fit)

#create a residual plot between age adjusted prevalance of smoking among people and age adjusted prevalance of High BP among people

plot( x, e, xlab = "ppl_smoking_age_adjusted_Prevalence", ylab = "ppl_BPHIGH_age_adjusted_prevalence", bg = "lightblue", col = "black", cex = 1, pch = 21, frame = FALSE,main = "residual plot for age adjusted prevalance of smoking among people and age adjusted prevalance of High BP among people",cex.main=0.7)


#add the regression lines

abline (h = 0, lwd = 2)

#draw the red lines

for (i in 1 : n) 
  lines (c(x[i], x[i]), c(e[i],0), col = "red", lwd = 1)

summary(fit)

 # Results before adding diabaites 
# Multiple R-squared:  0.3566,	adjusted R-squared:  0.354 
# F-statistic: 137.7 on 2 and 497 DF,  p-value: < 2.2e-16


 # Results after adding diabaites 
#Residual standard error: 3.47 on 497 degrees of freedom
#Multiple R-squared:  0.4526,	adjusted R-squared:  0.4504 
#F-statistic: 205.5 on 2 and 497 DF,  p-value: < 2.2e-16

```



```{r}

# Consider x as table1 = ppl_smoking_age_adjusted_Prevalence
# Consider y as table1 = ppl_Stroke_age_adjusted_prevalence

x <- ppl_smoking_age_adjusted_Prevalence
y <- ppl_Stroke_age_adjusted_prevalence

##plot x and y

plot( x, y, xlab = "ppl_smoking_age_adjusted_Prevalence", ylab = "ppl_Stroke_age_adjusted_prevalence",  bg = "lightblue", col = "black", cex = 1, pch = 21, frame = FALSE,main= "regression model for age adjusted prevalance of smoking among people and age adjusted prevalance of Stroke among people",cex.main=0.7)

n <- length (y)
fit <- lm(y ~ x+ ppl_BPHIGH_age_adjusted_prevalence )
e <- resid (fit)
yhat <- predict (fit)

#create a plot between the age adjusted prevalance of smoking among people and age adjusted prevalance of Stroke among people


plot( x, e, xlab = "ppl_smoking_age_adjusted_Prevalence", ylab = "ppl_Stroke_age_adjusted_prevalence", bg = "lightblue", col = "black", cex = 1, pch = 21, frame = FALSE,  main="residual plot for age adjusted prevalance of smoking among people and age adjusted prevalance of Stroke among people",cex.main=0.7)


#add the regression lines

abline (h = 0, lwd = 1)

#draw the red lines

for (i in 1 : n) 
  lines (c(x[i], x[i]), c(e[i],0), col = "red", lwd = 1)


summary(fit)

# Results Before adding high blood pressures

#Residual standard error: 0.4526 on 498 degrees of freedom
#Multiple R-squared:  0.6462,	adjusted R-squared:  0.6455 
#F-statistic: 909.7 on 1 and 498 DF,  p-value: < 1.2e-16

# Results after adding high blood pressures
#Residual standard error: 0.4181 on 497 degrees of freedom
#Multiple R-squared:  0.6987,	adjusted R-squared:  0.6975 
#F-statistic: 576.4 on 2 and 497 DF,  p-value: < 2.2e-16

# Explanation:


# smoking interact as a main reason for some disease, here we would like to study the smoking effect in (Asthma, high blood pressure ,Stroke) during our study for each case we noticed that there are some disease interact with smoking and might increase the chance of getting the second disease, 



#for the Highblood pressure we add the Diabaites effect and it show good fit, 

#For The Stroke beside the smoking we add the high blood pressure as second factor.

## we chose this model as good fit. from the three models the model with the best fit was using smoking to predict the Stroke and adding the Highblood pressure as a second factor, R-squared:  0.6975 since it is greater and the closest to 1.

##In this model, multiple R2 is 0.6987.It means, data variability is 69.87%


```



