---
title: "Week9"
author: "Talal Elammas"
author: "Hemangi Mhatre"

date: "March 31, 2019"
output: html_document
---



```{r}


## Save the data to a CSV file. 


##  Data were provided by the Centers for Disease Control and Prevention (CDC), Division of Population Health, Epidemiology and Surveillance Branch. The project was funded by the Robert Wood Johnson Foundation (RWJF) in conjunction with the CDC Foundation. 500 cities project city-level data in GIS-friendly format can be joined with city spatial data (https://chronicdata.cdc.gov/500-Cities/500-Cities-City-Boundaries/n44h-hy2j) in a geographic information system (GIS) to produce maps of 27 measures at the city-level. There are 4 measures (high blood pressure, taking high blood pressure medication, high cholesterol, cholesterol screening) in this 2018 release from the 2015 BRFSS that were the same as the 2017 release. 

# download the file, add it to your directory, update the directory in the , make sures the slash between directories is forword slash
# data Dictionary can be found on https://chronicdata.cdc.gov/500-Cities/500-Cities-City-level-Data-GIS-Friendly-Format-201/dxpw-cm5u

Project <- data.frame(read.csv(file =  'C:/Users/Talal/Documents/GitHub/Data_Visualization/Project/selecteddata.csv') , header = TRUE,  stringsAsFactors = FALSE)





```



```{r}
## 1: The question we maight answer the relation between cities and the prevelance rate of cancer disease  among population, distribuated in US cities in the given data. 

State <- c (Project[,1])
State
#as.character(State)
#toString(State)

city <- c (Project[,2])
city

PlaceFIPS <- c (Project[,3])
PlaceFIPS

population <- c (Project[,4])
population


ppl_No_Insurance <- c (Project[,5])
ppl_No_Insurance



ppl_BPHIGH <- c (Project[,6])


ppl_CANCER <- c (Project[,7])

ppl_CASTHMA <- c (Project[,8])
summary(Project)

#


```






```{r}
x<-lm(population ~ ppl_No_Insurance, Project)


x
```


```{r}


x<-lm(population ~ ppl_No_Insurance, Project)


x


# Consider x as table1 = Age
# Consider y as table1 = Resting Blood pressuer

x <- ppl_No_Insurance
y <- population
##plot x and y
plot( x, y, xlab = "age", ylab = "Resting Blood pressuer",  bg = "lightblue", col = "black", cex = 2, pch = 21, frame = FALSE)

n <- length (y)
fit <- lm(y ~ x)
e <- resid (fit)
yhat <- predict (fit)

#create a plot between the age and e



plot( x, e, xlab = "Age", ylab = "Resting Blood Pressure", bg = "lightblue", col = "black", cex = 2, pch = 21, frame = FALSE)


#add the regression lines

abline (h = 0, lwd = 2)

#draw the red lines

for (i in 1 : n) 
  lines (c(x[i], x[i]), c(e[i],0), col = "red", lwd = 2)


# as shown at age 52 people will likley got admitted to the hospitals with heart attacks and high resting blood pressure, while in age 63 they admitted with the same conditions and lowest resting blood pressure.

```


```{r}


# Consider x as table1 = Age
# Consider y as table1 = Resting Blood pressuer

x <- ppl_No_Insurance
y <- population
##plot x and y
plot( x, y, xlab = "age", ylab = "Resting Blood pressuer",  bg = "lightblue", col = "black", cex = 2, pch = 21, frame = FALSE)

n <- length (y)
fit <- lm(y ~ x)
e <- resid (fit)
yhat <- predict (fit)

#create a plot between the age and e

plot( x, e, xlab = "Age", ylab = "Resting Blood Pressure", bg = "lightblue", col = "black", cex = 2, pch = 21, frame = FALSE)


#add the regression lines

abline (h = 0, lwd = 2)

#draw the red lines

for (i in 1 : n) 
  lines (c(x[i], x[i]), c(e[i],0), col = "red", lwd = 2)


# as shown at age 52 people will likley got admitted to the hospitals with heart attacks and high resting blood pressure, while in age 63 they admitted with the same conditions and lowest resting blood pressure.

```


```{r}


# Consider x as table1 = Age
# Consider y as table1 = Resting Blood pressuer

x <- ppl_No_Insurance
y <- ppl_CANCER
##plot x and y
plot( x, y, xlab = "age", ylab = "Resting Blood pressuer",  bg = "lightblue", col = "black", cex = 2, pch = 21, frame = FALSE)

n <- length (y)
fit <- lm(y ~ x)
e <- resid (fit)
yhat <- predict (fit)

#create a plot between the age and e

plot( x, e, xlab = "Age", ylab = "Resting Blood Pressure", bg = "lightblue", col = "black", cex = 2, pch = 21, frame = FALSE)


#add the regression lines

abline (h = 0, lwd = 2)

#draw the red lines

for (i in 1 : n) 
  lines (c(x[i], x[i]), c(e[i],0), col = "red", lwd = 2)


# as shown at age 52 people will likley got admitted to the hospitals with heart attacks and high resting blood pressure, while in age 63 they admitted with the same conditions and lowest resting blood pressure.

```

